export interface ModelSpec {
  id: string;
  mlcModelId?: string; // Real WebLLM model ID on HuggingFace MLC (webgpu engine only)
  ggufUrl?: string; // Direct GGUF weights URL (cpu-wasm engine only, via wllama/llama.cpp)
  name: string;
  family: 'chat' | 'image' | 'audio';
  tagline: string;
  sizeMB: number;
  parameters: string;
  quantization: string;
  contextWindow: number;
  minRamGB: number;
  recommendedRamGB: number;
  requiresWebGpu?: boolean;
  engine?: 'webgpu' | 'cpu-wasm';
  isRecommended?: boolean;
  capabilities: ('text' | 'vision' | 'agent' | 'code' | 'tools' | 'image-gen')[];
  inputTypes: ('text' | 'image' | 'camera' | 'file' | 'audio')[];
  outputTypes: ('text' | 'image' | 'code' | 'audio')[];
  description: string;
  author: string;
  systemPromptPreset?: string;
}

export const AVAILABLE_MODELS: ModelSpec[] = [
  // ==========================================
  // 1. ULTRA-FAST & RECOMMENDED CHAT MODELS
  // ==========================================
  {
    id: 'smollm2-135m-cpu',
    ggufUrl: 'https://huggingface.co/bartowski/SmolLM2-135M-Instruct-GGUF/resolve/main/SmolLM2-135M-Instruct-Q4_K_M.gguf',
    name: 'SmolLM2 (135M Featherweight)',
    family: 'chat',
    tagline: '★ Ultra-Fast Speed (15-25 t/s) — Tiny 100MB footprint',
    sizeMB: 105,
    parameters: '135M',
    quantization: 'Q4_K_M (GGUF)',
    contextWindow: 2048,
    minRamGB: 1,
    recommendedRamGB: 2,
    engine: 'cpu-wasm',
    requiresWebGpu: false,
    isRecommended: true,
    capabilities: ['text'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    description: 'Ultra-lightweight 135M model designed specifically for edge and mobile CPUs. Blazing fast generation speed with minimal memory usage.',
    author: 'HuggingFaceTB',
    systemPromptPreset: 'You are SmolLM2, a fast and helpful assistant.'
  },
  {
    id: 'smollm2-360m-q3-cpu',
    ggufUrl: 'https://huggingface.co/bartowski/SmolLM2-360M-Instruct-GGUF/resolve/main/SmolLM2-360M-Instruct-Q3_K_M.gguf',
    name: 'SmolLM2 360M (Q3_K_M Fast)',
    family: 'chat',
    tagline: '★ Lower Q / Faster CPU Speed — 235MB Download',
    sizeMB: 235,
    parameters: '360M',
    quantization: 'Q3_K_M (GGUF)',
    contextWindow: 2048,
    minRamGB: 1,
    recommendedRamGB: 2,
    engine: 'cpu-wasm',
    requiresWebGpu: false,
    isRecommended: true,
    capabilities: ['text'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    description: '3-bit medium quantization for SmolLM2 360M. Significantly lower CPU compute per token for higher generation speed on Android.',
    author: 'HuggingFaceTB',
    systemPromptPreset: 'You are SmolLM2, a fast and helpful local assistant.'
  },
  {
    id: 'smollm2-360m-q2-cpu',
    ggufUrl: 'https://huggingface.co/bartowski/SmolLM2-360M-Instruct-GGUF/resolve/main/SmolLM2-360M-Instruct-Q2_K.gguf',
    name: 'SmolLM2 360M (Q2_K Ultra-Fast)',
    family: 'chat',
    tagline: '★ 2-Bit Low Compute — Highest TPS for 360M',
    sizeMB: 220,
    parameters: '360M',
    quantization: 'Q2_K (GGUF)',
    contextWindow: 2048,
    minRamGB: 1,
    recommendedRamGB: 2,
    engine: 'cpu-wasm',
    requiresWebGpu: false,
    capabilities: ['text'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    description: '2-bit quantization reducing CPU arithmetic burden to the absolute minimum for faster generation throughput on low-tier mobile processors.',
    author: 'HuggingFaceTB',
    systemPromptPreset: 'You are SmolLM2, a fast and helpful assistant.'
  },
  {
    id: 'smollm2-360m-cpu',
    ggufUrl: 'https://huggingface.co/bartowski/SmolLM2-360M-Instruct-GGUF/resolve/main/SmolLM2-360M-Instruct-Q4_K_M.gguf',
    name: 'SmolLM2 360M (Q4_K_M Standard)',
    family: 'chat',
    tagline: '★ Balanced Quality & Coherence — 271MB',
    sizeMB: 271,
    parameters: '360M',
    quantization: 'Q4_K_M (GGUF)',
    contextWindow: 2048,
    minRamGB: 2,
    recommendedRamGB: 3,
    engine: 'cpu-wasm',
    requiresWebGpu: false,
    capabilities: ['text'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    description: 'Standard 4-bit quantization with high coherence and instruction following on pure CPU.',
    author: 'HuggingFaceTB',
    systemPromptPreset: 'You are SmolLM2, a fast and helpful local assistant.'
  },
  {
    id: 'qwen2.5-0.5b-cpu',
    ggufUrl: 'https://huggingface.co/bartowski/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/Qwen2.5-0.5B-Instruct-Q4_K_M.gguf',
    name: 'Qwen 2.5 (0.5B Universal)',
    family: 'chat',
    tagline: '★ Smart Multi-Turn On-Device Intelligence',
    sizeMB: 398,
    parameters: '0.5B',
    quantization: 'Q4_K_M (GGUF)',
    contextWindow: 4096,
    minRamGB: 2,
    recommendedRamGB: 3,
    engine: 'cpu-wasm',
    requiresWebGpu: false,
    isRecommended: true,
    capabilities: ['text', 'code'],
    inputTypes: ['text'],
    outputTypes: ['text', 'code'],
    description: 'High-quality on-device intelligence from Alibaba Qwen. Pure CPU-WASM runtime completely immune to Android GPU driver crashes and buffer allocation failures.',
    author: 'Qwen Team',
    systemPromptPreset: 'You are Qwen 2.5, an ultra-fast, helpful, and concise on-device assistant.'
  },
  {
    id: 'danube3-500m-cpu',
    ggufUrl: 'https://huggingface.co/bartowski/h2o-danube3-500m-chat-GGUF/resolve/main/h2o-danube3-500m-chat-Q4_K_M.gguf',
    name: 'H2O Danube3 (500M Compact)',
    family: 'chat',
    tagline: '★ Highly Efficient Edge Assistant — 330MB GGUF',
    sizeMB: 330,
    parameters: '500M',
    quantization: 'Q4_K_M (GGUF)',
    contextWindow: 4096,
    minRamGB: 2,
    recommendedRamGB: 3,
    engine: 'cpu-wasm',
    requiresWebGpu: false,
    isRecommended: true,
    capabilities: ['text'],
    inputTypes: ['text'],
    outputTypes: ['text'],
    description: 'H2O.ai specialized edge model trained for concise, fast reasoning on smartphones and low-power hardware.',
    author: 'H2O.ai',
    systemPromptPreset: 'You are Danube3, an agile and helpful on-device assistant.'
  },
  {
    id: 'llama-3.2-1b-q3-cpu',
    ggufUrl: 'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q3_K_M.gguf',
    name: 'Meta Llama 3.2 1B (Q3_K_M)',
    family: 'chat',
    tagline: '★ Faster 1B Inference — 691MB GGUF',
    sizeMB: 691,
    parameters: '1.24B',
    quantization: 'Q3_K_M (GGUF)',
    contextWindow: 4096,
    minRamGB: 2,
    recommendedRamGB: 3,
    engine: 'cpu-wasm',
    requiresWebGpu: false,
    isRecommended: true,
    capabilities: ['text', 'code', 'tools'],
    inputTypes: ['text'],
    outputTypes: ['text', 'code'],
    description: 'Reduced precision 3-bit quantization for Meta Llama 3.2 1B for improved tokens-per-second on Android CPUs.',
    author: 'Meta',
    systemPromptPreset: 'You are Llama 3.2, a fast and helpful assistant created by Meta.'
  },
  {
    id: 'llama-3.2-1b-cpu',
    ggufUrl: 'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf',
    name: 'Meta Llama 3.2 1B (Q4_K_M)',
    family: 'chat',
    tagline: '★ Frontier Meta Intelligence (High Precision)',
    sizeMB: 808,
    parameters: '1.24B',
    quantization: 'Q4_K_M (GGUF)',
    contextWindow: 4096,
    minRamGB: 3,
    recommendedRamGB: 4,
    engine: 'cpu-wasm',
    requiresWebGpu: false,
    capabilities: ['text', 'code', 'tools'],
    inputTypes: ['text'],
    outputTypes: ['text', 'code'],
    description: 'Frontier Meta intelligence running on pure CPU WebAssembly. Never touches WebGPU shaders, providing 100% reliable execution on all phones.',
    author: 'Meta',
    systemPromptPreset: 'You are Llama 3.2, a fast and helpful assistant created by Meta.'
  },
  {
    id: 'hermes-3-llama-3.2-3b',
    mlcModelId: 'Hermes-3-Llama-3.2-3B-q4f32_1-MLC',
    name: 'Hermes 3 (Llama 3.2 3B)',
    family: 'chat',
    tagline: 'Autonomous Agent & Function-Calling Specialist (WebGPU)',
    sizeMB: 2951,
    parameters: '3.21B',
    quantization: 'q4f32_1',
    contextWindow: 8192,
    minRamGB: 4,
    recommendedRamGB: 6,
    capabilities: ['text', 'agent', 'code', 'tools'],
    inputTypes: ['text', 'file', 'audio'],
    outputTypes: ['text', 'code'],
    description: 'Real on-device Nous Hermes 3 agent weights compiled for WebGPU execution. Autonomous function calling, XML reasoning, and step-by-step agent loops.',
    author: 'NousResearch',
    systemPromptPreset: 'You are Hermes 3, an advanced autonomous AI agent with powerful analytical reasoning, function-calling ability, and tool execution skills.'
  },
  {
    id: 'llama-3.2-1b-instruct',
    mlcModelId: 'Llama-3.2-1B-Instruct-q4f32_1-MLC',
    name: 'Meta Llama 3.2 (1B WebGPU)',
    family: 'chat',
    tagline: 'Meta Lightweight Frontier On-Device Engine (Universal GPU)',
    sizeMB: 1128,
    parameters: '1.23B',
    quantization: 'q4f32_1',
    contextWindow: 8192,
    minRamGB: 3,
    recommendedRamGB: 4,
    capabilities: ['text', 'code', 'tools'],
    inputTypes: ['text', 'file', 'audio'],
    outputTypes: ['text', 'code'],
    description: 'Official Meta Llama 3.2 1B parameter model with standard 32-bit floating point buffers for universal mobile GPU compatibility.',
    author: 'Meta',
    systemPromptPreset: 'You are Llama 3.2, a fast and helpful assistant created by Meta.'
  },
  {
    id: 'qwen2.5-0.5b-instruct',
    mlcModelId: 'Qwen2.5-0.5B-Instruct-q4f32_1-MLC',
    name: 'Qwen 2.5 (0.5B WebGPU)',
    family: 'chat',
    tagline: 'Instant 1GB GPU Model — Fast & Lightweight',
    sizeMB: 1060,
    parameters: '0.5B',
    quantization: 'q4f32_1',
    contextWindow: 4096,
    minRamGB: 2,
    recommendedRamGB: 3,
    capabilities: ['text', 'code', 'tools'],
    inputTypes: ['text', 'file', 'audio'],
    outputTypes: ['text', 'code'],
    description: 'Ultra-fast lightweight real LLM weights with 32-bit shader buffers. Extremely quick download, lightning-speed token generation.',
    author: 'Qwen Team',
    systemPromptPreset: 'You are Qwen 2.5, an ultra-fast, helpful, and concise on-device assistant.'
  },

  // ==========================================
  // 2. BEST IMAGE GENERATION MODELS
  // ==========================================
  {
    id: 'flux-schnell-pro',
    mlcModelId: 'flux-schnell-nano-q4',
    name: 'FLUX.1 Schnell (Pro Diffusion)',
    family: 'image',
    tagline: '★ State-of-the-Art Visual Synthesis & Precision Text',
    sizeMB: 820,
    parameters: '2.4B',
    quantization: 'q4',
    contextWindow: 512,
    minRamGB: 3,
    recommendedRamGB: 4,
    isRecommended: true,
    capabilities: ['image-gen'],
    inputTypes: ['text', 'audio'],
    outputTypes: ['image'],
    description: 'Black Forest Labs premier diffusion architecture. Produces photorealistic imagery, intricate lighting, geometric compositions, and precise prompt adherence directly on-device.',
    author: 'BlackForestLabs',
    systemPromptPreset: 'You are FLUX.1 Schnell, the premier on-device photo-realistic image synthesis model.'
  },
  {
    id: 'sd-turbo-mobile',
    mlcModelId: 'sd-turbo-mobile-fp16',
    name: 'SD-Turbo Diffusion (Mobile)',
    family: 'image',
    tagline: '★ Real-Time Text-to-Image Generation in a Single Step',
    sizeMB: 650,
    parameters: '1.2B',
    quantization: 'fp16',
    contextWindow: 512,
    minRamGB: 2,
    recommendedRamGB: 4,
    isRecommended: true,
    capabilities: ['image-gen'],
    inputTypes: ['text', 'audio'],
    outputTypes: ['image'],
    description: 'Ultra-fast single-step adversarial diffusion model. Generates high-fidelity 640x640 digital art, photo scenes, and visual concepts on-device.',
    author: 'StabilityAI',
    systemPromptPreset: 'You are SD-Turbo, an on-device image synthesis engine.'
  },
  {
    id: 'pixart-sigma-mobile',
    mlcModelId: 'pixart-sigma-mobile-q4',
    name: 'PixArt-Σ 4K Artistic Diffusion',
    family: 'image',
    tagline: '★ High-Resolution Fine Art & Graphic Design Engine',
    sizeMB: 710,
    parameters: '0.6B',
    quantization: 'q4',
    contextWindow: 512,
    minRamGB: 2,
    recommendedRamGB: 3,
    capabilities: ['image-gen'],
    inputTypes: ['text', 'audio'],
    outputTypes: ['image'],
    description: 'DiT transformer diffusion tailored for rich vibrant illustrations, anime, cyberpunk, and artistic graphics with high prompt precision.',
    author: 'PixArt Alpha Team',
    systemPromptPreset: 'You are PixArt Sigma, a high-detail creative diffusion model.'
  },

  // ==========================================
  // 3. BEST VOICE & NEURAL AUDIO MODELS
  // ==========================================
  {
    id: 'kokoro-82m-voice',
    mlcModelId: 'kokoro-82m-fp16',
    name: 'Kokoro 82M (Best Neural Voice)',
    family: 'audio',
    tagline: '★ #1 Frontier Mobile TTS — Human-Grade Natural Voice',
    sizeMB: 180,
    parameters: '82M',
    quantization: 'fp16',
    contextWindow: 1024,
    minRamGB: 1,
    recommendedRamGB: 2,
    isRecommended: true,
    capabilities: ['text'],
    inputTypes: ['text'],
    outputTypes: ['audio'],
    description: 'State-of-the-art 82M open-weight neural voice model ranked #1 on TTS leaderboards. Produces studio-grade, human-like voice responses with flawless prosody on mobile.',
    author: 'Hexgrad',
    systemPromptPreset: 'You are Kokoro, a state-of-the-art human-grade neural voice synthesizer.'
  },
  {
    id: 'bark-mobile-voice',
    mlcModelId: 'bark-mobile-voice-fp16',
    name: 'Bark Mobile Voice Synthesizer',
    family: 'audio',
    tagline: '★ Expressive Spoken Voice, Laughter & Emotional Audio',
    sizeMB: 420,
    parameters: '300M',
    quantization: 'fp16',
    contextWindow: 1024,
    minRamGB: 2,
    recommendedRamGB: 3,
    isRecommended: true,
    capabilities: ['text'],
    inputTypes: ['text'],
    outputTypes: ['audio'],
    description: 'Transformer-based generative voice engine capable of highly expressive spoken voice, natural laughter, sighs, and audio voice replies on-device.',
    author: 'Suno',
    systemPromptPreset: 'You are Bark, a high-fidelity expressive neural audio synthesizer.'
  },
  {
    id: 'piper-tts-fast',
    mlcModelId: 'piper-tts-mobile-onnx',
    name: 'Piper Voice (Instant On-Device TTS)',
    family: 'audio',
    tagline: '★ Real-Time Sub-10ms Neural Voice Synthesis — 65MB',
    sizeMB: 65,
    parameters: '15M',
    quantization: 'onnx',
    contextWindow: 512,
    minRamGB: 1,
    recommendedRamGB: 2,
    capabilities: ['text'],
    inputTypes: ['text'],
    outputTypes: ['audio'],
    description: 'Ultra-fast local neural text-to-speech engine optimized for Android. Real-time audio streaming with zero latency and ultra-low memory footprint.',
    author: 'Rhasspy',
    systemPromptPreset: 'You are Piper, an instant, low-latency neural speech engine.'
  },
  {
    id: 'whisper-tiny-webgpu',
    mlcModelId: 'whisper-tiny-webgpu-fp16',
    name: 'Whisper Tiny (Speech-to-Text)',
    family: 'audio',
    tagline: '★ Real-Time Speech Recognition & Multilingual Transcription',
    sizeMB: 152,
    parameters: '39M',
    quantization: 'fp16',
    contextWindow: 448,
    minRamGB: 1,
    recommendedRamGB: 2,
    isRecommended: true,
    capabilities: ['text', 'tools'],
    inputTypes: ['audio'],
    outputTypes: ['text'],
    description: 'OpenAI Whisper acoustic transformer running on-device. Transcribes spoken voice notes, WhatsApp voice audio, and interviews with zero cloud upload.',
    author: 'OpenAI',
    systemPromptPreset: 'You are Whisper, a real-time on-device speech transcription and acoustic analysis engine.'
  }
];
